url: https://imagitor.github.io
baseurl: /booleanbites/

# Site settings
title: BooleanBites Ltd
email: info@booleanbites.com
description: "BooleanBites Ltd is a team of highly skilled professional to serve our clients by developing on demand Software Solutions. We at BooleanBites are well aware of latest tools and technologies for development, project management, task management, versioning control, quality assurance and project methodologies."


# Team names, titles and social links
#people:
#- name: Adil Soomro
#  pic: 1
#  position: Co Founder
#  social:
#    - title: twitter
#      url: twitter.com/adil_soomro

# - name: Tahir Jilani
#   pic: 2
#   position: Co Founder
#   social:
#     - title: twitter
#       url: twitter.com/TAHIRJILANI


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/booleanbites
  - title: facebook
    url: https://facbeook.com/booleanbitesltd
  - title: linkedin
    url: https://www.linkedin.com/company/booleanbites-ltd

# Postal address (add as many lines as necessary)
address:
  - line: Johar Town
  - line: Lahore, Pakistan

# Build settings
markdown: kramdown
permalink: pretty
